import Clean.Circuit
import Clean.Utils.Primes
import Ragu.Circuits.Element.AllocSquare
import Ragu.Circuits.Element.Mul

namespace Ragu.Circuits.Point.Alloc
variable {p : ℕ} [Fact p.Prime]

structure Point (F : Type) where
  x : F
  y : F
deriving ProvableStruct

def main (_input : Unit) : Circuit (F p) (Var Point (F p)) := do

  let ⟨x, x2⟩ <- subcircuit Ragu.Circuits.Element.AllocSquare.circuit default
  let x3 <- subcircuit Ragu.Circuits.Element.Mul.circuit ⟨x, x2⟩
  let ⟨y, y2⟩ <- subcircuit Ragu.Circuits.Element.AllocSquare.circuit default

  -- NOTE: the constant (5 * 1) is not simplified to 5 to syntactically
  -- match constraints generated by Ragu
  assertZero ((x3 + (5 * 1)) - y2)
  return ⟨x, y⟩


def Assumptions (_input : Unit) := True

def Spec (_input : Unit) (out : Point (F p)) :=
  out.y * out.y = out.x * out.x * out.x + 5

-- #eval! main (p:=pBabybear) default |>.operations 0 |>.toFlat
instance elaborated : ElaboratedCircuit (F p) unit Point where
  main
  localLength _ := 9

theorem soundness : Soundness (F p) elaborated Assumptions Spec := by
  circuit_proof_start
  sorry

theorem completeness : Completeness (F p) elaborated Assumptions := by
  sorry

def circuit : FormalCircuit (F p) unit Point :=
  { elaborated with Assumptions, Spec, soundness, completeness }

end Ragu.Circuits.Point.Alloc
